appVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: web
  ports:
    - port: 3000    # This is the port that the service will listen on
      targetPort: 3000   # This is the port that the service will forward traffic to

# The service will listen on port 3000 and forward traffic to port 3000 on the pods that have the label component: web
