apiVersion: app/v1
kind: Deployment
metadata:
  name: client-deployment 
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web   # This is the label that the pods will have for front end
  template:
    metadata:
      labels:
        component: web   # This is the label that the pods will have for front end
    spec:
    containers:
    - name: client
      image: stephengrider/multi-client
      ports:
      - containerPort: 3000
      

