apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:  # This should be at the same level as metadata
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: stephengrider/multi-server
          ports:
            - containerPort: 5000  # Add the container port here
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres 
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGHOST
              value: '5432'
            - name: PGDATABASE
              value: postgres
              value From :
              secretkeyRef:
                name: pgpassword
                key: PGPASSWORD
