apiversion: apps/v1
kind: Deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: my-worker-image
          ports:
            - containerPort: 8080